#!/bin/bash
: <<'DESCRIPTION'
Setups up kubeconfig for specific cluster

BOOTSTRAP VERSION: 0.0.3

PARAMETERS
- EKS CLUSTER_NAME

Requires
- awscli
- jq
- kubectl

USAGE: ./kubeconfig cluster-name
DESCRIPTION

export SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export CLUSTER_NAME=$1

source $SCRIPT_DIR/functions
export REGION=$(get_cluster_region $CLUSTER_NAME)

aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION
